# Generated by Django 4.1.7 on 2023-03-17 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Key',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=1000)),
                ('Website_Name', models.CharField(blank=True, max_length=1000, null=True)),
                ('Meta_Desc', models.CharField(blank=True, max_length=1000, null=True)),
                ('Favicon', models.ImageField(blank=True, null=True, upload_to='Logo')),
                ('Logo', models.ImageField(blank=True, null=True, upload_to='Logo')),
                ('Email', models.EmailField(blank=True, max_length=1000, null=True)),
                ('Facebook', models.CharField(blank=True, max_length=1000, null=True)),
                ('Instagram', models.CharField(blank=True, max_length=1000, null=True)),
                ('Twitter', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
