# Generated by Django 4.1.7 on 2023-03-19 01:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_post_like_follow_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='follow',
            name='roomcode',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
